version: '2'

services:

  ### Applications Code Container #############################

  applications:
    image: lzssing/true
    volumes:
    - ./:/var/www

  ### Workspace Utilities Container ###########################

  workspace:
    image: lzssing/workspace
    volumes_from:
    - applications
    extra_hosts:
    - "dockerhost:10.0.75.1"
    ports:
    - "22"
    tty: true
    networks:
    - frontend
    - backend

  ### PHP-FPM Container #######################################

  php-fpm:
    image: lzssing/php-fpm
    volumes_from:
    - applications
    expose:
    - "9000"
    depends_on:
    - workspace
    extra_hosts:
    - "dockerhost:10.0.75.1"
    environment:
    - PHP_IDE_CONFIG=laradock
    networks:
    - backend

  ### NGINX Server Container ##################################

  nginx:
    image: lzssing/nginx
    volumes_from:
    - applications
    volumes:
    - ../logs/nginx/:/var/log/nginx
    ports:
    - "80:80"
    - "443"
    depends_on:
    - php-fpm
    networks:
    - frontend
    - backend

  ### MySQL Container #########################################

  mysql:
    image: lzssing/mysql
    environment:
    - MYSQL_DATABASE=study
    - MYSQL_USER=root
    - MYSQL_PASSWORD=docker.18
    - MYSQL_ROOT_PASSWORD=docker.18
    volumes:
    - ../data/mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"
