@extends('auth.privacy.parent')
@section('main')
    <div class="row">
        <div class="col-md-8">
            <h2 class="_353a _52ip _52id _3m9" style="font-size: 40px; margin: 0px; padding: 0px 0px 19px; line-height: 48px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> Data Policy </h2>
            <p> This policy describes the information we process to support Facebook, Instagram, Messenger and other products and features offered by Facebook (<a href="https://www.facebook.com/help/1561485474074139?ref=dp" style="color: rgb(66, 103, 178); cursor: pointer; font-family: inherit;">Facebook Products</a>&nbsp;or Products). You can find additional tools and information in the&nbsp;<a href="https://www.facebook.com/settings" style="color: rgb(66, 103, 178); cursor: pointer; font-family: inherit;">Facebook Settings</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fprivacy_and_security%2F&amp;h=AT0c1kW0ULFB4Y7seev5vYRER3yFC4aWO2vIbCalDWX8QRlvey4NtYbrhmb-Bfy4COxYfpUodBG_btM3ptcsupPbfsb0w4mwSUL3wCi19VudvXfS7YsEIU_Mh0dpiW9E4yQ98riqTd-NI5q408pv2nRtLw4" target="_blank" style="color: rgb(66, 103, 178); cursor: pointer; font-family: inherit;">Instagram Settings</a>. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(108, 160, 182); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> What kinds of information do we collect? </h3>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>To provide the Facebook Products, we must process information about you. The types of information we collect depend on how you use our Products. You can learn how to access and delete information we collect by visiting the&nbsp;<a href="https://www.facebook.com/settings" style="cursor: pointer; font-family: inherit;">Facebook Settings</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fprivacy_and_security%2F&amp;h=AT0rGjb0Hv4BUA4gkO0IZWaNgLxnQV2K0aJ0FZjM0tzfE--uNaM8kpjVm1N27AfjhlRCVr9uy6ZSy2uYpPlFNcT1mwTHuJQXI_OSFnq_HVrtioq1Wn00TSdb9mOmrMCxe57_jNFC7olYR9XzUqTvBv9CbIM" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Settings</a>. </p>
            <p> Things you and others do and provide. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <ul class="uiList _4of _4kg list-paddingleft-2" style="list-style-position: initial; list-style-image: initial; margin-left: 6px; padding: 0px; color: black; margin-block-end: 12px; margin-block-start: 12px;">
                <li> <p> <span style="font-weight: 600;">Information and content you provide.</span>&nbsp;We collect the content, communications and other information you provide when you use our Products, including when you sign up for an account, create or share content, and message or communicate with others. This can include information in or about the content you provide (like metadata), such as the location of a photo or the date a file was created. It can also include what you see through features we provide, such as our&nbsp;<a href="https://www.facebook.com/help/162347444215311" style="cursor: pointer; font-family: inherit;">camera</a>, so we can do things like suggest masks and filters that you might like, or give you tips on using camera formats. Our systems automatically process content and communications you and others provide to analyze context and what's in them for the purposes described&nbsp;<a href="https://www.lnmpa.top/facebook/privacy_policy#how-we-use-information" style="cursor: pointer; font-family: inherit;">below</a>. Learn more about how you can control who can see the things you&nbsp;<a href="https://www.facebook.com/help/1297502253597210?ref=dp" style="cursor: pointer; font-family: inherit;">share</a>. </p> </li>
                <ul class="uiList _4of _4kg list-paddingleft-2" style="list-style-type: square;">
                    <li> <p> Data with special protections: You can choose to provide information in your Facebook&nbsp;<a href="https://www.facebook.com/help/353111348061173?ref=dp" style="cursor: pointer; font-family: inherit;">profile fields</a>&nbsp;or Life Events about your religious views, political views, who you are &quot;interested in,&quot; or your health. This and other information (such as racial or ethnic origin, philosophical beliefs or trade union membership) could be subject to special protections under the laws of your country. </p> </li>
                </ul>
                <li> <p> <span style="font-weight: 600;">Networks and connections.</span>&nbsp;We collect information about the people,&nbsp;<a href="https://www.facebook.com/help/282489752085908?ref=dp" style="cursor: pointer; font-family: inherit;">Pages</a>, accounts,&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F351460621611097%3Fref%3Ddp&amp;h=AT14GDx7a4iBdnhALiwyoQmBqhnnts5IcP3XynWl1f6OV2Rg8bHGYs5xtJJ9pmRkV9s17NYi7U5phAnCRzY2D25prioySxk_rLYBi-4CN9fJvk36f96KXkEjz4qLCXtJ5J4TeUMBSjPT7oRMxSY3TyJai3k" target="_blank" style="cursor: pointer; font-family: inherit;">hashtags</a>&nbsp;and groups you are connected to and how you interact with them across our Products, such as people you communicate with the most or groups you are part of. We also collect contact information if you&nbsp;<a href="https://www.facebook.com/help/561688620598358?ref=dp" style="cursor: pointer; font-family: inherit;">choose to upload, sync or import it from a device</a>&nbsp;(such as an address book or call log or SMS log history), which we use for things like helping you and others find people you may know and for the other purposes listed&nbsp;<a href="https://www.lnmpa.top/facebook/privacy_policy#how-we-use-information" style="cursor: pointer; font-family: inherit;">below</a>. </p> </li>
                <li> <p> <span style="font-weight: 600;">Your usage.</span>&nbsp;We collect information about how you use our Products, such as the types of content you view or engage with; the features you use; the actions you take; the people or accounts you interact with; and the time, frequency and duration of your activities. For example, we log when you're using and have last used our Products, and what posts, videos and other content you view on our Products. We also collect information about how you use features like our camera. </p> </li>
                <li> <p> <span style="font-weight: 600;">Information about transactions made on our Products.</span>&nbsp;If you use our Products for&nbsp;<a href="https://www.facebook.com/help/1434403039959381?ref=dp" style="cursor: pointer; font-family: inherit;">purchases</a>&nbsp;or other financial transactions (such as when you make a purchase in a game or make a&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fdonations.fb.com%2F&amp;h=AT1VRtNE2drWsHMqnXxrchx8Nrwvx87P1ikqOIfMwDRHe2Rj8APvAS6BcBV-KAzjoat9O2g_qXNw4VWmITz840cB2BumQnpNUHqFaWr0fu48t3t7lQFcypjehWwXAeAPJhOtgJcdK5SXARgtS9fbG6vPGLI" target="_blank" style="cursor: pointer; font-family: inherit;">donation</a>), we collect information about the purchase or transaction. This includes payment information, such as your credit or debit card number and other card information; other account and authentication information; and billing, shipping and contact details. </p> </li>
                <li> <p> <span style="font-weight: 600;">Things others do and information they provide about you.</span>&nbsp;We also receive and analyze content, communications and information that other people provide when they use our Products. This can include information about you, such as when others share or comment on a photo of you, send a message to you, or upload, sync or import your contact information. </p> </li>
            </ul>
            <p> Device Information </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>As described below, we collect information from and about the computers, phones, connected TVs and other web-connected devices you use that integrate with our Products, and we combine this information across different devices you use. For example, we use information collected about your use of our Products on your phone to better personalize the content (including&nbsp;<a href="https://www.facebook.com/help/119468292028768?ref=dp" style="cursor: pointer; font-family: inherit;">ads</a>) or features you see when you use our Products on another device, such as your laptop or tablet, or to measure whether you took an action in response to an ad we showed you on your phone on a different device.&nbsp;<br /><br />Information we obtain from these devices includes:&nbsp;<br /><br /> </p>
            <ul class="uiList _4of _4kg list-paddingleft-2" style="margin-left: 6px; padding: 0px; color: rgb(0, 0, 0);">
                <li> <p> <span style="font-weight: 600;">Device attributes:</span>&nbsp;information such as the operating system, hardware and software versions, battery level, signal strength, available storage space, browser type, app and file names and types, and plugins. </p> </li>
                <li> <p> <span style="font-weight: 600;">Device operations:</span>&nbsp;information about operations and behaviors performed on the device, such as whether a window is foregrounded or backgrounded, or mouse movements (which can help distinguish humans from bots). </p> </li>
                <li> <p> <span style="font-weight: 600;">Identifiers:</span>&nbsp;unique identifiers, device IDs, and other identifiers, such as from games, apps or accounts you use, and Family Device IDs (or other identifiers unique to&nbsp;<a href="https://www.facebook.com/help/195227921252400?ref=dp" style="cursor: pointer; font-family: inherit;">Facebook Company Products</a>&nbsp;associated with the same device or account). </p> </li>
                <li> <p> <span style="font-weight: 600;">Device signals:</span>&nbsp;Bluetooth signals, and information about nearby Wi-Fi access points, beacons, and cell towers. </p> </li>
                <li> <p> <span style="font-weight: 600;">Data from device settings:</span>&nbsp;information you allow us to receive through device settings you turn on, such as access to your GPS location, camera or photos. </p> </li>
                <li> <p> <span style="font-weight: 600;">Network and connections:</span>&nbsp;information such as the name of your mobile operator or ISP, language, time zone, mobile phone number, IP address, connection speed and, in some cases, information about other devices that are nearby or on your network, so we can do things like help you&nbsp;<a href="https://www.facebook.com/help/276515126152168?ref=dp" style="cursor: pointer; font-family: inherit;">stream a video from your phone to your TV</a>. </p> </li>
                <li> <p> <span style="font-weight: 600;">Cookie data:</span>&nbsp;data from cookies stored on your device, including cookie IDs and settings. Learn more about how we use cookies in the&nbsp;<a href="https://www.facebook.com/policies/cookies/" style="cursor: pointer; font-family: inherit;">Facebook Cookies Policy</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Flegal%2Fcookies%2F&amp;h=AT3OMy2Ke13nvDy9K8LnGih82NFKu9u7UAOWl_OFnGeDlh2UUkEFCoyZim45fha45uemNc-PWroM2pbQczaKU5kbBH3fjz2yC78w6R2DQp-FL0H6d2uz4lwG7gbfSU7zy1hL7MWU6jNd0iistfe9aqyT5Kg" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Cookies Policy</a>. </p> </li>
            </ul>
            <p> Information from partners. </p>
            <p> Advertisers,&nbsp;<a href="https://www.facebook.com/help/1642635852727373?ref=dp" style="cursor: pointer; font-family: inherit;">app</a>&nbsp;developers, and publishers can send us information through&nbsp;<a href="https://www.facebook.com/help/331509497253087" style="cursor: pointer; font-family: inherit;">Facebook Business Tools</a>&nbsp;they use, including our social plug-ins (such as the Like button), Facebook Login, our&nbsp;<a href="https://developers.facebook.com/docs/apis-and-sdks" style="cursor: pointer; font-family: inherit;">APIs and SDKs</a>, or the Facebook&nbsp;<a href="https://www.facebook.com/business/a/facebook-pixel" style="cursor: pointer; font-family: inherit;">pixel</a>. These partners provide information about your activities off Facebook—including information about your device, websites you visit, purchases you make, the ads you see, and how you use their services—whether or not you have a Facebook account or are logged into Facebook. For example, a game developer could use our API to tell us what games you play, or a business could tell us about a purchase you made in its store. We also receive information about your online and offline actions and purchases from third-party data providers who have the rights to provide us with your information.&nbsp;<br /><br />Partners receive your data when you visit or use their services or through third parties they work with. We require each of these partners to have lawful rights to collect, use and share your data before providing any data to us.&nbsp;<a href="https://www.facebook.com/help/494750870625830?ref=dp" style="cursor: pointer; font-family: inherit;">Learn more</a>&nbsp;about the types of partners we receive data from.&nbsp;<br /><br />To learn more about how we use cookies in connection with Facebook Business Tools, review the&nbsp;<a href="https://www.facebook.com/policies/cookies" style="cursor: pointer; font-family: inherit;">Facebook Cookies Policy</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Flegal%2Fcookies%2F&amp;h=AT08SySvvFBRpqFBuQeYG-SiMWtQoAOvLOl-vvIpuriY7wMjXS3edIwxbMXjg55U9UypmgXoKxE6lg9c1QkurX_oHPuEcxU-vUwxKEhuDSL1vAVJbhdahNCWjRi8yWd2lcsQSpzn3u9tSJo44sVGoySgvko" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Cookies Policy</a>. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(233, 120, 91); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How do we use this information? </h3>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>We use the information we have (subject to choices you make) as described below and to provide and support the Facebook Products and related services described in the&nbsp;<a href="https://www.facebook.com/legal/terms/update" style="cursor: pointer; font-family: inherit;">Facebook Terms</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F581066165581870%3Fref%3Ddp&amp;h=AT2tedY7TCNJgEK4zkgj3bMVikMOXqFNRDsErO00yIOnKDSuhuNsy9b230cgayQ1ABggBp7vWBlp8dn8rOfoHq2in9PseQ2GCj-7Ss9fb2M7_0oslo6Q-t2Fyryiyj38WQITc3qkJdrijN5INPXcMQZfZAQ" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Terms</a>. Here's how: </p>
            <p> Provide, personalize and improve our Products. </p>
            <p> We use the information we have to deliver our Products, including to personalize features and content (including your&nbsp;<a href="https://www.facebook.com/help/166738576721085?ref=dp" style="cursor: pointer; font-family: inherit;">News Feed</a>,&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F1986234648360433%3Fref%3Ddp&amp;h=AT1M_rKVauAsfgYzpzMj4U3TlYe6kgmoreWWHrSIcq-nKwZaMN4sEfM3REKf6iFedv1YDfqJo9kJxSj9xmupxswpdM2Vl1fz0SAsxufkPFze41iXoTzo6gwq2HpMV1Pbwr_hUmVBmjIABHa_jaR5EVpHSdM" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Feed</a>, Instagram Stories and ads) and make suggestions for you (such as groups or&nbsp;<a href="https://www.facebook.com/help/1076296042409786?ref=dp" style="cursor: pointer; font-family: inherit;">events</a>&nbsp;you may be interested in or topics you may want to follow) on and off our Products. To create personalized Products that are unique and relevant to you, we use your connections, preferences, interests and activities based on the data we collect and learn from you and others (including any&nbsp;<a href="https://www.lnmpa.top/facebook/privacy_policy#data-special-protections" style="cursor: pointer; font-family: inherit;">data with special protections</a>&nbsp;you choose to provide); how you use and interact with our Products; and the people, places, or things you're connected to and interested in on and off our Products. Learn more about how we use information about you to personalize your Facebook and Instagram experience, including features, content and recommendations in Facebook Products; you can also learn more about how we choose the&nbsp;<a href="https://www.facebook.com/about/ads" style="cursor: pointer; font-family: inherit;">ads</a>&nbsp;that you see. </p>
            <ul class="uiList _4of _4kg list-paddingleft-2" style="list-style-position: initial; list-style-image: initial; margin-left: 6px; padding: 0px; color: black; margin-block-end: 12px; margin-block-start: 12px;">
                <li> <p> <span style="font-weight: 600;">Information across Facebook Products and devices:</span>&nbsp;We connect information about your activities on different Facebook Products and devices to provide a more tailored and consistent experience on all Facebook Products you use, wherever you use them. For example, we can suggest that you join a group on Facebook that includes people you follow on Instagram or communicate with using Messenger. We can also make your experience more seamless, for example, by automatically filling in your registration information (such as your phone number) from one Facebook Product when you sign up for an account on a different Product. </p> </li>
                <li> <p> <span style="font-weight: 600;">Location-related information:</span>&nbsp;We use&nbsp;<a href="https://www.facebook.com/about/basics/manage-your-privacy/location" style="cursor: pointer; font-family: inherit;">location-related information</a>-such as your current location, where you live, the places you like to go, and the businesses and people you're near-to provide, personalize and improve our Products,&nbsp;<a href="https://www.facebook.com/about/ads" style="cursor: pointer; font-family: inherit;">including ads</a>, for you and others. Location-related information can be based on things like precise device location (if you've allowed us to collect it), IP addresses, and information from your and others' use of Facebook Products (such as check-ins or events you attend). </p> </li>
                <li> <p> <span style="font-weight: 600;">Product research and development:</span>&nbsp;We use the information we have to develop, test and improve our Products, including by conducting surveys and research, and testing and troubleshooting new products and features. </p> </li>
                <li> <p> <span style="font-weight: 600;">Face recognition:</span>&nbsp;If you have it turned on, we use face recognition technology to recognize you in photos, videos and camera experiences. The face-recognition templates we create may constitute&nbsp;<a href="https://www.lnmpa.top/facebook/privacy_policy#data-special-protections" style="cursor: pointer; font-family: inherit;">data with special protections</a>&nbsp;under the laws of your country. Learn more about&nbsp;<a href="https://www.facebook.com/help/218540514842030?ref=dp" style="cursor: pointer; font-family: inherit;">how we use face recognition technology</a>, or control our use of this technology in&nbsp;<a href="https://www.facebook.com/settings/facerec" style="cursor: pointer; font-family: inherit;">Facebook Settings</a>. If we introduce face-recognition technology to your Instagram experience, we will let you know first, and you will have control over whether we use this technology for you. </p> </li>
                <li> <p> <span style="font-weight: 600;">Ads and other sponsored content:</span>&nbsp;We use the information we have about you-including information about your interests, actions and connections-to select and personalize ads, offers and other sponsored content that we show you. Learn more about how we&nbsp;<a href="https://www.facebook.com/ads/preferences" style="cursor: pointer; font-family: inherit;">select and personalize ads</a>, and your choices over the data we use to select ads and other sponsored content for you in the&nbsp;<a href="https://www.facebook.com/settings" style="cursor: pointer; font-family: inherit;">Facebook Settings</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fprivacy_and_security%2F&amp;h=AT1LxHWdzhbe2Ltr8e75_DakrTUXoc275oeH4cFpNdjLy7vifrI9SDI9Yati4UzqNcDXsGT8gUj5bLqOBL9Z2B1RDOofV4gGN8BK1AKC-g52qhativUp5_bjons57sk5E4F80WI8ccoHqnuDZJ2sbbvO2uA" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Settings</a>. </p> </li>
            </ul>
            <p> Provide measurement, analytics, and other business services. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>We use the information we have (including your activity off our Products, such as the websites you visit and ads you see) to help advertisers and other partners measure the effectiveness and distribution of their ads and services, and understand the types of people who use their services and how people interact with their websites, apps, and services.&nbsp;<a href="https://www.lnmpa.top/facebook/privacy_policy#sharing-partner-information" style="cursor: pointer; font-family: inherit;">Learn how we share information</a>&nbsp;with these partners. </p>
            <p> Promote safety, integrity and security. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>We use the information we have to verify accounts and activity, combat harmful conduct, detect and prevent spam and other bad experiences, maintain the integrity of our Products, and promote safety and security on and off of Facebook Products. For example, we use data we have to investigate suspicious activity or violations of our terms or policies, or to&nbsp;<a href="https://code.facebook.com/posts/286893341840510/under-the-hood-suicide-prevention-tools-powered-by-ai/" style="cursor: pointer; font-family: inherit;">detect when someone needs help</a>. To learn more, visit the&nbsp;<a href="https://www.facebook.com/help/379220725465972?ref=dp" style="cursor: pointer; font-family: inherit;">Facebook Security Help Center</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F369001149843369&amp;h=AT2loqqgEJhqFjjetWZ-sJhEpPhoztcITua2K2oh0r0wTIh1ktoHmxZH-Vo5ktq1hB9Vm1vVwBMKvleKGOUQ1Zf9Vx9yrxZFUqggdsBBQ6Z95iDeDn71dE4NvEuQ2tg1yBOL9tyW2G-nqZcjkFFfqXX84w0" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Security Tips</a>. </p>
            <p> Communicate with you. </p>
            <p> We use the information we have to send you marketing communications, communicate with you about our Products, and let you know about our policies and terms. We also use your information to respond to you when you contact us. </p>
            <p> Research and innovate for social good. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>We use the information we have (including from research partners we collaborate with) to conduct and support&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fresearch.fb.com%2F&amp;h=AT25rbbr-g38lE-1jTmKe9I6wA7j03iu2O9b329y05ZFvvWno88BencZdXaF6JRs5y2LY8oRviZZtJFyRFn_qMC8ISJIJnGXzLxxVEbHJZ9yp16ZpLYf15th93lNunPmRxYHuSFMXsewyskNDjb5vc2thHJKxBUSGBZ6jb54" target="_blank" style="cursor: pointer; font-family: inherit;">research</a>&nbsp;and innovation on topics of general social welfare, technological advancement, public interest, health and well-being. For example,&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fresearch.fb.com%2Ffacebook-disaster-maps-methodology%2F&amp;h=AT2DPtI9_N47br-cwyt90IPN8Zf2qgAovdOZ8y9tBouiTN-HXyjJmG2WUbIr3KLKKG1d9jRi3LkzsNnCxMWRwBY69RwpGsbN1D_m3wvsxyt-YK40ydC0cel4Bsa53bQMYPaROKs-udAfl5zPuqaRNQdM3nk" target="_blank" style="cursor: pointer; font-family: inherit;">we analyze information we have about migration patterns during crises</a>&nbsp;to aid relief efforts.&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fresearch.fb.com%2F&amp;h=AT2eTHdztos2IuuGwQY6Pa9IMz7Dyufyw128dsyAF42tZCxY_14caecd0_Yxox9hzCmdHAFKJ0EeiB25ScGG8upx99O-TQsC83jd4VEEV4JH-b6DjCPTjVyWyv0Jf3LVwB_3SJVkQIkyN56_8yveGCBAAcg" target="_blank" style="cursor: pointer; font-family: inherit;">Learn more</a>&nbsp;about our research programs. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(49, 163, 141); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How is this information shared? </h3>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>Your information is shared with others in the following ways:&nbsp;<br /><br /> </p>
            <p> Sharing on Facebook Products </p>
            <p> People and accounts you share and communicate with </p>
            <p> When you share and communicate using our Products,&nbsp;<a href="https://www.facebook.com/help/120939471321735?ref=dp" style="cursor: pointer; font-family: inherit;">you choose the audience for what you share</a>. For example, when you post on Facebook, you select the audience for the post, such as a group, all of your friends, the public, or a customized list of people. Similarly, when you use Messenger or Instagram to communicate with people or businesses, those people and businesses can see the content you send. Your network can also see actions you have taken on our Products, including engagement with ads and sponsored content. We also let other accounts see who has viewed their Facebook or Instagram Stories.&nbsp;<br /><br /><span style="font-weight: 600;"><a href="https://www.facebook.com/help/203805466323736?ref=dp" style="cursor: pointer; font-family: inherit;">Public information</a></span>&nbsp;can be seen by anyone, on or off our Products, including if they don't have an account. This includes your Instagram username; any information you share with a public audience; information in your&nbsp;<a href="https://www.facebook.com/help/203805466323736?ref=dp" style="cursor: pointer; font-family: inherit;">public profile on Facebook</a>; and content you share on a Facebook Page,&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F448523408565555%3Fref%3Ddp&amp;h=AT0sGZeNlMLhsFA6qQW40jZngGG0cuC28iiZIZe2FwJ2A6fyfD9NwCmXKuYZ7fQ4hUIor9mBbCzJXRTdH7L9ZHROemvkxZeBbS8E2kvZmXYOZfXyb7DEIzmI7To1SXUXLIUNgHNfXUz_0uapBlUwsHUgvEU" target="_blank" style="cursor: pointer; font-family: inherit;">public Instagram account</a>&nbsp;or any other public forum, such as&nbsp;<a href="https://www.facebook.com/marketplace" style="cursor: pointer; font-family: inherit;">Facebook Marketplace</a>. You, other people using Facebook and Instagram, and we can provide access to or send public information to anyone on or off our Products, including in other Facebook Company Products, in search results, or through tools and APIs. Public information can also be seen, accessed, reshared or downloaded through third-party services such as search engines, APIs, and offline media such as TV, and by apps, websites and other services that integrate with our Products.&nbsp;<br /><br />Learn more about what information is public and how to control your visibility on&nbsp;<a href="https://www.facebook.com/help/203805466323736?ref=dp" style="cursor: pointer; font-family: inherit;">Facebook</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F243810329323104%3Fref%3Ddp&amp;h=AT35xTW-b5ExTfcE_8yhZgzgq90pAi3CrKDjLZ0gzh0-1k8BJO-ikkgDgC3N2eXaSb3MTJ1zQSTIbCW0ey03IXwXbFLO6a1WMu6NEhJpNEYpuRcfSlgTJPkNs_mibHkfUb90hexiZ9lnI7k3VlU8lHBtJB4" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram</a>. </p>
            <p> Content others share or reshare about you </p>
            <p> You should consider who you choose to share with, because people who can see your activity on our Products can choose to share it with others on and off our Products, including people and businesses outside the audience you shared with. For example, when you share a post or send a message to specific friends or accounts, they can download, screenshot, or reshare that content to others across or off our Products, in person or in virtual reality experiences such as&nbsp;<a href="https://www.facebook.com/help/241256606347754?ref=dp" style="cursor: pointer; font-family: inherit;">Facebook Spaces</a>. Also, when you comment on someone else's post or react to their content, your comment or reaction is visible to anyone who can see the other person's content, and that person can change the audience later.&nbsp;<br /><br />People can also use our Products to create and share content about you with the audience they choose. For example, people can share a photo of you in a Story, mention or tag you at a location in a post, or share information about you in their posts or messages. If you are uncomfortable with what others have shared about you on our Products, you can learn how to&nbsp;<a href="https://www.facebook.com/help/181495968648557?ref=dp" style="cursor: pointer; font-family: inherit;">report the content</a>. </p>
            <p> Information about your active status or presence on our Products. </p>
            <p> People in your networks can see signals telling them whether you are active on our Products, including whether you are currently active on&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F906123729538696%3Fref%3Ddp&amp;h=AT2TgvTugWIv9nKRCTrPUdfgsWfODfvJXits7g_YnBcFRdhU8QivgsrVIQt_w3xCQp7MOVqt4xqoPv9J8l3Zb3w8oHwGzEG4pKbpXU2qT2HjVgf6loq0YPKatIUqSgSjc9xfO9iZ8iR5uSTRY1paKR1pH-Y" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram</a>,&nbsp;<a href="https://www.facebook.com/help/149081061827062?ref=dp" style="cursor: pointer; font-family: inherit;">Messenger</a>&nbsp;or Facebook, or when you last used our Products. </p>
            <p> Apps, websites, and third-party integrations on or using our Products. </p>
            <p> When you choose to use third-party apps, websites, or other services that use, or are integrated with, our Products, they can receive information about what you post or share. For example, when you play a game with your Facebook friends or use a Facebook Comment or Share button on a website, the game developer or website can receive information about your activities in the game or receive a comment or link that you share from the website on Facebook. Also, when you download or use such third-party services, they can access your&nbsp;<a href="https://www.facebook.com/help/203805466323736?ref=dp" style="cursor: pointer; font-family: inherit;">public profile</a>&nbsp;on Facebook, and any information that you share with them. Apps and websites you use may receive your list of Facebook friends if you choose to share it with them. But apps and websites you use will not be able to receive any other information about your Facebook friends from you, or information about any of your Instagram followers (although your friends and followers may, of course, choose to share this information themselves). Information collected by these third-party services is subject to their own terms and policies, not this one.&nbsp;<br /><br />Devices and operating systems providing native versions of Facebook and Instagram (i.e. where we have not developed our own first-party apps) will have access to all information you choose to share with them, including information your friends share with you, so they can provide our core functionality to you.&nbsp;<br /><br /><em>Note: We are in the process of restricting developers’ data access even further to help prevent abuse. For example, we will remove developers' access to your Facebook and Instagram data if you haven't used their app in 3 months, and we are changing Login, so that in the next version, we will reduce the data that an app can request without app review to include only name, Instagram username and bio, profile photo and email address. Requesting any other data will require our approval.</em> </p>
            <p> New owner. </p>
            <p> If the ownership or control of all or part of our Products or their assets changes, we may transfer your information to the new owner. </p>
            <p> <br /> </p>
            <p> Sharing with Third-Party Partners </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a>We work with third-party partners who help us provide and improve our Products or who use Facebook Business Tools to grow their businesses, which makes it possible to operate our companies and provide free services to people around the world. We don't sell any of your information to anyone, and we never will. We also impose strict restrictions on how our partners can use and disclose the data we provide. Here are the types of third parties we share information with:&nbsp;<br /> </p>
            <p> Partners who use our analytics services. </p>
            <p> We provide aggregated statistics and insights that help people and businesses understand how people are engaging with their posts, listings, Pages, videos and other content on and off the Facebook Products. For example, Page admins and Instagram business profiles receive information about the number of people or accounts who viewed, reacted to, or commented on their posts, as well as aggregate demographic and other information that helps them understand interactions with their Page or account. </p>
            <p> Advertisers. </p>
            <p> We provide advertisers with reports about the kinds of people seeing their ads and how their ads are performing, but we don't share information that personally identifies you (information such as your name or email address that by itself can be used to contact you or identifies who you are) unless you give us permission. For example, we provide general demographic and interest information to advertisers (for example, that an ad was seen by a woman between the ages of 25 and 34 who lives in Madrid and likes software engineering) to help them better understand their audience. We also confirm which Facebook ads led you to make a purchase or take an action with an advertiser. </p>
            <p> Measurement partners. </p>
            <p> We share information about you with companies that aggregate it to provide analytics and measurement reports to our partners. </p>
            <p> Partners offering goods and services in our Products. </p>
            <p> When you subscribe to receive premium content, or buy something from a seller in our Products, the content creator or seller can receive your public information and other information you share with them, as well as the information needed to complete the transaction, including shipping and contact details. </p>
            <p> Vendors and service providers. </p>
            <p> We provide information and content to vendors and service providers who support our business, such as by providing technical infrastructure services, analyzing how our Products are used, providing customer service, facilitating payments or conducting surveys. </p>
            <p> Researchers and academics. </p>
            <p> We also provide information and content to research partners and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fresearch.fb.com%2Fprograms%2F&amp;h=AT1OK3_AGpUCrbrfY-gJTGqRkX23OYDzJ8GrueRauila7eKuJqlMQixcYUJAKN7hYvrONbxUtoU4Ao_m27g_IOE-Zhadz0Te8z600fbU2QoGr88qSrg3X0ooQqHqkStKq7SZEhbNOTG3GyQZn-ZKtdNyKlI" target="_blank" style="cursor: pointer; font-family: inherit;">academics</a>&nbsp;to conduct research that advances scholarship and innovation that support our business or mission, and enhances discovery and innovation on topics of general social welfare, technological advancement, public interest, health and well-being. </p>
            <p> Law enforcement or legal requests. </p>
            <p> We share information with law enforcement or in response to legal requests in the circumstances outlined&nbsp;<a href="https://www.lnmpa.top/facebook/privacy_policy#legal-requests-prevent-harm" style="cursor: pointer; font-family: inherit;">below</a>. </p>
            <p> Learn more about how you can control the information about you that you or others share with third-party partners in the&nbsp;<a href="https://www.facebook.com/settings" style="cursor: pointer; font-family: inherit;">Facebook Settings</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fprivacy_and_security%2F&amp;h=AT2cg1iELHrhLps6oczuNLBDaMgLh4tHKihxCPtejurZkMi4jVUmmOwQn6vC9a-DiRRMBz-4XuzbOldeCGVJv-TOB6kFpaJtyE2bnf0eZcMaL9BIfjHFFHCzSWgmYuplxQ0QxzmGXeasW9gYpLUGRknBs_4" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Settings</a>. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(243, 107, 127); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How do the Facebook Companies work together? </h3>
            <p> Facebook and Instagram share infrastructure, systems and technology with other&nbsp;<a href="https://www.facebook.com/help/111814505650678?ref=dp" style="cursor: pointer; font-family: inherit;">Facebook Companies</a>&nbsp;(which include WhatsApp and Oculus) to provide an innovative, relevant, consistent and safe experience across all&nbsp;<a href="https://www.facebook.com/help/195227921252400?ref=dp" style="cursor: pointer; font-family: inherit;">Facebook Company Products</a>&nbsp;you use. We also process information about you across the Facebook Companies for these purposes, as permitted by applicable law and in accordance with their terms and policies. For example, we process information from WhatsApp about accounts sending spam on its service so we can take appropriate action against those accounts on Facebook, Instagram or Messenger. We also work to understand how people use and interact with Facebook Company Products, such as understanding the number of unique users on different Facebook Company Products. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(233, 120, 91); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How can I manage or delete information about me? </h3>
            <p> We provide you with the ability to access, rectify, port and erase your data. Learn more in your&nbsp;<a href="https://www.facebook.com/settings" style="cursor: pointer; font-family: inherit;">Facebook Settings</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fprivacy_and_security%2F&amp;h=AT0slqMeSfBAJMz9t6RNazthPClzcuV7JUFMl2ikejTt9o8sy4WAV5qoVMKwsq7uX6cqySvnuH1RXU78gL8pfp88s8eA7KdoBKRZVPCeHjkLiWD4J-vewG6_0dwBSf1blXekYUCPjndbsEv7X-R-81xFgvs" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Settings</a>.&nbsp;<br /><br />We store data until it is no longer necessary to provide our services and Facebook Products, or until your account is deleted - whichever comes first. This is a case-by-case determination that depends on things like the nature of the data, why it is collected and processed, and relevant legal or operational retention needs. For example, when you search for something on Facebook, you can access and delete that query from within your search history at any time, but the log of that search is deleted after 6 months. If you submit a copy of your government-issued ID for account verification purposes, we delete that copy 30 days after submission. Learn more about deletion of&nbsp;<a href="https://www.facebook.com/help/356107851084108?ref=dp" style="cursor: pointer; font-family: inherit;">content you have shared</a>&nbsp;and&nbsp;<a href="https://www.facebook.com/help/206635839404055?ref=dp" style="cursor: pointer; font-family: inherit;">cookie data obtained through social plugins</a>.&nbsp;<br /><br />When you delete your account, we&nbsp;<a href="https://www.facebook.com/help/356107851084108?ref=dp" style="cursor: pointer; font-family: inherit;">delete things</a>&nbsp;you have posted, such as your photos and status updates, and you won't be able to recover that information later. Information that others have shared about you isn't part of your account and won't be deleted. If you don't want to delete your account but want to temporarily stop using the Products, you can deactivate your account instead. To delete your account at any time, please visit the&nbsp;<a href="https://www.facebook.com/settings" style="cursor: pointer; font-family: inherit;">Facebook Settings</a>&nbsp;and&nbsp;<a href="https://www.instagram.com/accounts/privacy_and_security/" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Settings</a>. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(250, 200, 162); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How do we respond to legal requests or prevent harm? </h3>
            <p> We access, preserve and share your information with regulators, law enforcement or others: </p>
            <ul class="uiList _4of _4kg list-paddingleft-2" style="list-style-position: initial; list-style-image: initial; margin-left: 6px; padding: 0px; color: black; margin-block-end: 12px; margin-block-start: 12px;">
                <li> <p> In response to a legal request (like a search warrant, court order or subpoena) if we have a good faith belief that the law requires us to do so. This may include responding to legal requests from jurisdictions outside of the United States when we have a good-faith belief that the response is required by law in that jurisdiction, affects users in that jurisdiction, and is consistent with internationally recognized standards. </p> </li>
                <li> <p> When we have a good-faith belief it is necessary to: detect, prevent and address fraud, unauthorized use of the Products, violations of our terms or policies, or other harmful or illegal activity; to protect ourselves (including our rights, property or Products), you or others, including as part of investigations or regulatory inquiries; or to prevent death or imminent bodily harm. For example, if relevant, we provide information to and receive information from third-party partners about the reliability of your account to prevent fraud, abuse and other harmful activity on and off our Products. </p> </li>
            </ul>
            <p> Information we receive about you (including financial transaction data related to purchases made with Facebook) can be accessed and preserved for an extended period when it is the subject of a legal request or obligation, governmental investigation, or investigations of possible violations of our terms or policies, or otherwise to prevent harm. We also retain information from accounts disabled for terms violations for at least a year to prevent repeat abuse or other term violations. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(128, 212, 196); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How do we operate and transfer data as part of our global services? </h3>
            <p> We share information globally, both internally within the Facebook Companies, and externally with our partners and with those you connect and share with around the world in accordance with this policy. Your information may, for example, be transferred or transmitted to, or stored and processed in the United States or other countries outside of where you live for the purposes as described in this policy. These data transfers are necessary to provide the services set forth in the&nbsp;<a href="https://www.facebook.com/legal/terms/" style="cursor: pointer; font-family: inherit;">Facebook Terms</a>&nbsp;and&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fhelp.instagram.com%2F581066165581870%3Fref%3Ddp&amp;h=AT2TeWApS5BX6nqRihj_-1iPJX1s5mCaGwdELV3ZnxTarnFkZSvbvy2PR0oR7bo6lAKl0eU6mBkt-8WbwYxG0GL3nJm1AEz6B3mRbD4LIFwmQOQfzBH6qYcoiApyJ9w39Y4k2l3Zqi1i0TtfhjJiLClRxv8" target="_blank" style="cursor: pointer; font-family: inherit;">Instagram Terms</a>and to globally operate and provide our Products to you. We utilize&nbsp;<a href="https://l.facebook.com/l.php?u=http%3A%2F%2Feur-lex.europa.eu%2Flegal-content%2FEN%2FTXT%2FPDF%2F%3Furi%3DCELEX%3A32010D0087&amp;h=AT05U-2349AZGZj4FvOyQkT73zFHlti8NHHMPjFCAh1u-La42mnB3oySVkqpuUI_EVNjjyjtR2ZZLuVff6lDsTTa7g6YaGEo8mPY-n9C27ztTT5Nz5-XjQLlgq5D8ONgsYxkOuQI1QRKNyg351QEZzgILkI" target="_blank" style="cursor: pointer; font-family: inherit;">standard contract clauses</a>, rely on the European Commission's&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fec.europa.eu%2Finfo%2Flaw%2Flaw-topic%2Fdata-protection%2Fdata-transfers-outside-eu%2Fadequacy-protection-personal-data-non-eu-countries_en&amp;h=AT2cPb8xAy9hS7HWA2-Rhd__h-tyeFHSt5ryk0loi-vNMoD6rwTD8JmWqIDnVOxbDJi7Xcq3PYt2MZ2-zYgNy_Xvvwwt-b47F_zTmX_J3ZfU437SYr-W-gsho1OlaijA7u6cHe5rcBKQvRaDM5unr6I8fIM" target="_blank" style="cursor: pointer; font-family: inherit;">adequacy decisions</a>&nbsp;about certain countries, as applicable, and obtain your consent for these data transfers to the United States and other countries. </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;"></a> </p>
            <p> <a href="https://www.lnmpa.top/facebook/privacy_policy#" style="cursor: pointer; font-family: inherit;">Return to top</a> </p>
            <p></p>
            <h3 class="_3x94 _52io _3m9" style="color: rgb(24, 109, 144); font-size: 36px; margin: 0px 0px 24px; padding: 0px; line-height: 44px; text-rendering: optimizelegibility; font-family: inherit; font-weight: normal !important;"> How will we notify you of changes to this policy? </h3>
            <p> We'll notify you before we make changes to this policy and give you the opportunity to review the revised policy before you choose to continue using our Products. </p>
            <p> <br /> </p>
        </div>
        <div class="col-md-4"></div>
    </div>
@endsection
